=== DeusMagi/deusmagi-server/maps/schemas/ads-1.dtd
<!ELEMENT interfaces (interface*, quest?)>

<!ELEMENT quest (interface*, part*)>
<!ATTLIST quest
        name CDATA #REQUIRED
        repeat (1|0) #IMPLIED
        repeat_delay CDATA #IMPLIED>

<!ELEMENT part (info?, item?, kill?, interface*, part*)>
<!ATTLIST part
        uid CDATA #REQUIRED
        name CDATA #REQUIRED>

<!ELEMENT info (#PCDATA)>

<!ELEMENT item EMPTY>
<!ATTLIST item
        arch CDATA #IMPLIED
        name CDATA #IMPLIED
        nrof CDATA #IMPLIED
        keep (1|0) #IMPLIED>

<!ELEMENT kill EMPTY>
<!ATTLIST kill
        nrof CDATA #IMPLIED>

<!ELEMENT interface (code?, and?, dialog*)>
<!ATTLIST interface
        inherit CDATA #IMPLIED
        npc CDATA #IMPLIED
        state CDATA #IMPLIED>

<!ELEMENT code (#PCDATA)>

<!ELEMENT and (and|or|check|ncheck|message|choice|object|inherit|response|
        action|notification|close|say)*>

<!ELEMENT or (and|or|check|ncheck)*>

<!ELEMENT check (object?)>
<!ATTLIST check
        region_map CDATA #IMPLIED
        enemy (any|player) #IMPLIED
        started CDATA #IMPLIED
        finished CDATA #IMPLIED
        completed CDATA #IMPLIED
        failed CDATA #IMPLIED
        options CDATA #IMPLIED
        num2finish CDATA #IMPLIED
        faction_friend CDATA #IMPLIED
        gender (male|female|neuter|hermaphrodite) #IMPLIED)

<!ELEMENT ncheck (object?)>
<!ATTLIST ncheck
        region_map CDATA #IMPLIED
        enemy (any|player) #IMPLIED
        started CDATA #IMPLIED
        finished CDATA #IMPLIED
        completed CDATA #IMPLIED
        failed CDATA #IMPLIED
        options CDATA #IMPLIED
        num2finish CDATA #IMPLIED
        faction_friend CDATA #IMPLIED
        gender (male|female|neuter|hermaphrodite) #IMPLIED)

<!ELEMENT precond (#PCDATA)>

<!ELEMENT dialog ((message|choice|object|inherit|response|action|
        notification|close|say|and))>
<!ATTLIST dialog
        name CDATA #IMPLIED
        regex CDATA #IMPLIED
        inherit CDATA #IMPLIED
        icon CDATA #IMPLIED
        title CDATA #IMPLIED
        animation CDATA #IMPLIED>

<!ELEMENT message (#PCDATA,object*)>
<!ATTLIST message
        color CDATA #IMPLIED>

<!ELEMENT choice (message*)>

<!ELEMENT object EMPTY>
<!ATTLIST object
        arch CDATA #IMPLIED
        name CDATA #IMPLIED
        message CDATA #IMPLIED
        nrof CDATA #IMPLIED
        remove CDATA #IMPLIED>

<!ELEMENT inherit EMPTY>
<!ATTLIST inherit
        name CDATA #IMPLIED>

<!ELEMENT response EMPTY>
<!ATTLIST response
        message CDATA #REQUIRED
        destination CDATA #IMPLIED
        action CDATA #IMPLIED
        npc CDATA #IMPLIED>

<!ELEMENT action (#PCDATA)>
<!ATTLIST action
        start CDATA #IMPLIED
        complete CDATA #IMPLIED
        fail CDATA #IMPLIED
        region_map CDATA #IMPLIED
        enemy (player|clear) #IMPLIED
        teleport CDATA #IMPLIED
        trigger CDATA #IMPLIED
        cast CDATA #IMPLIED>

<!ELEMENT notification EMPTY>
<!ATTLIST notification
        message CDATA #REQUIRED
        action CDATA #IMPLIED
        shortcut CDATA #IMPLIED
        delay CDATA #IMPLIED>

<!ELEMENT close EMPTY>

<!ELEMENT say (#PCDATA)>

=== DeusMagi/deusmagi-server/maps/interfaces/quests/frevia_tomboyish_fairy/quest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <quest name="Frevia's Tomboyish Fairy">
        <interface inherit="Merchant.Seller" npc="Frevia">
            <dialog name="hello">
                <message>Oh, hello there again, {self.gender}!</message>
                <inherit name="::goods"/>
            </dialog>
            <dialog name="::stockin">
                <message>Would you like to buy one of my flowers?</message>
            </dialog>
            <dialog name="::stockout">
                <message>I'm sorry, I'm all out of flowers right now!</message>
            </dialog>
            <dialog name="::stockoutitem">
                <message>Oh dear, I don't have any {self.buy_item.name} left!</message>
            </dialog>
        </interface>
        <interface npc="Tomboyish Fairy">
            <dialog name="hello">
                <message>Eye'm the strongest!</message>
                <response destination="the strongest" message="You're the strongest?"/>
                <response destination="not the strongest" message="No way, that's impossible!"/>
                <response destination="strongest fairy" message="You're the strongest fairy... maybe."/>
                <response destination="idiot" message="What?  Are you dumb or something?"/>
                <response action="close" message="Goodbye."/>
            </dialog>
            <dialog name="the strongest">
                <choice>
                    <message>Yay!</message>
                    <message>Yeah. I'm the best.</message>
                    <message>There are no buses in Gensokyo.</message>
                    <message>Eye'm a genius!</message>
                    <message>So, what was I doing, again...?</message>
                </choice>
                <response destination="hello" message="OK."/>
                <response destination="idiot" message="Well, that was stupid."/>
                <response action="close" message="Goodbye."/>
            </dialog>
            <dialog inherit="the strongest" regex="(strong|cirno)"/>
            <dialog name="not the strongest">
                <choice>
                    <message>Eye said Eye'm the strongest!</message>
                    <message>I'll cryo-freeze you along with some English beef!</message>
                    <message>This atmosphere... it smells like WAR!</message>
                    <message>I'm going to beat you for that.</message>
                    <message>Freeze to death! Freeze to death!</message>
                </choice>
                <response destination="hello" message="Whatever."/>
                <response destination="idiot" message="You must be stupid or something."/>
                <response action="close" message="Goodbye."/>
            </dialog>
            <dialog inherit="not the strongest" regex="(weak|strongest fairy)"/>
            <dialog name="idiot">
                <choice>
                    <message>Hey!  Eye'm not dumb.</message>
                    <message>The one saying &quot;idiot&quot; is an idiot.</message>
                </choice>
                <response destination="hello" message="OK."/>
                <response destination="idiot" message="That was childish."/>
                <response action="close" message="Goodbye."/>
            </dialog>
            <dialog inherit="idiot" regex="(baka|nineball|marukyuu|\(9\))"/>
        </interface>
        <part name="The Fairy" uid="find_fairy">
            <info>Frevia, an elven shyde with home in a glade east of Aris, has asked you to find her missing fairy. She has suggested to look near a small lake south of the glade.</info>
            <interface npc="Frevia" state="need_start">
                <dialog name="hello">
                    <message>Oh, hello there, wandering stranger! You're welcome to stay a while and rest in my glade, if you like.</message>
                    <message>However, I do have to ask... Have you, by any chance, seen my little fairy? She has been missing for a while now, and I'm beginning to worry...</message>
                    <response destination="havefairies" message="You seem to have a few fairies around right here."/>
                </dialog>
                <dialog name="havefairies">
                    <message>Oh no, I don't mean these!</message>
                    <message color="yellow">{npc.name} the elven shyde giggles softly to herself.</message>
                    <message>This one was... special, shall we say... always had a mind of her own, bit tomboyish really.</message>
                    <response destination="lookfor" message="I could look for her."/>
                    <response action="close" message="Farewell."/>
                </dialog>
                <dialog name="lookfor">
                    <message>You would! Thank you, kind {self.gender2}!</message>
                    <message>I think my little fairy has taken a liking to the small lake south of my glade, near a large waterfall. Perhaps she will be around there...</message>
                    <action start="find_fairy"/>
                </dialog>
            </interface>
            <interface npc="Frevia" state="need_complete">
                <dialog name="hello">
                    <message>Have you found my little fairy yet, kind {self.gender2}?</message>
                    <response destination="working" message="Working on it."/>
                </dialog>
                <dialog name="working">
                    <message>I think she has taken a liking to the small lake south of my glade, near a large waterfall. Perhaps she will be around there...</message>
                    <response action="close" message="Farewell."/>
                </dialog>
            </interface>
            <interface inherit="interface" npc="Tomboyish Fairy" state="need_complete">
                <dialog name="hello">
                    <response destination="oneof" message="Are you one of Frevia's fairies?"/>
                    <inherit/>
                </dialog>
                <dialog name="oneof">
                    <message>Humpf, what if I am?!</message>
                    <response destination="lookingfor" message="She's looking for you."/>
                </dialog>
                <dialog name="lookingfor">
                    <message>Oh, is she now!</message>
                    <response destination="worried" message="She's worried about you."/>
                </dialog>
                <dialog name="worried">
                    <message>There's no reason to be worried about me...</message>
                    <message color="yellow">{npc.name} grins mischievously.</message>
                    <message>Tell Frevia she needn't worry about me. I'll be around the glade from time to time...</message>
                    <action start="report"/>
                    <action complete="find_fairy"/>
                </dialog>
            </interface>
        </part>
        <part name="Report to Frevia" uid="report">
            <info>You have found the fairy safe and sound, exactly where Frevia said she would be. You should report the good news to Frevia.</info>
            <interface npc="Frevia" state="need_complete">
                <dialog name="hello">
                    <message>Have you found my little fairy yet, kind {self.gender2}?</message>
                    <response destination="safe" message="Yes, she's safe and sound at the lake."/>
                </dialog>
                <dialog name="safe">
                    <message>Ah, I see! Thank you, I appreciate your kindness, dear {self.gender2}. It will be nice to see her again from time to time, like I said, she's a bit of a rebel...</message>
                    <message>As a token of my gratitude, please accept this flower from me. As you may know, flowers are a powerful symbol among the elves, but the flowers from this glade are even more special...</message>
                    <action complete="report"/>
                    <object arch="mythical_scarlet_pimpernel_flower"/>
                </dialog>
            </interface>
        </part>
    </quest>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/centennial/sakura.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface inherit="Temple.TempleTerria">
        <dialog name="reimu" regex="reimu|hakurei|reimu hakurei">
            <message color="yellow">{npc.name} blushes.</message>
            <message>Yeah, I kinda feel like she's kindred spirit or something.</message>
            <message color="yellow">{npc.name} glances over at donations.</message>
        </dialog>
        <dialog name="kinomoto" regex="kinomoto|sakura kinomoto">
            <message>Oh, fine... I'll say it.</message>
            <message color="yellow">{npc.name} grabs a baton with a star on it and does a dance.</message>
            <message color="pink">&quot;Keiyaku no moto Sakura ga mejiru. Release!&quot;</message>
            <message>There. Happy?</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/brynknot/achetran.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Hello there, adventurer. I'm {npc.name}, the mage. Are you, like myself, interested in this extraordinary hole?</message>
            <response destination="yes" message="Yes..."/>
            <response action="close" message="No."/>
        </dialog>
        <dialog name="yes">
            <message>I see... Well, the hole has appeared quite recently after a strong earthquake hit the area... I dare not go in just yet, but there seems to be a lot of static in the air down there.</message>
            <response destination="static" message="Static?"/>
        </dialog>
        <dialog name="static">
            <message>Yes, electricity... It is quite possible there are the mythical crystals down there.</message>
            <response destination="crystals" message="Tell me about these crystals..."/>
        </dialog>
        <dialog name="crystals">
            <message>The crystals are said to transform air around them into electricity over time, then release the electricity all at once... This is supposedly to give energy to the main crystal, which will also harden, making it nearly impossible to shatter...</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/brynknot/sam_goodberry.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>At last! We're here in Brynknot, {activator.name}. A large world awaits you. If you wish to sail back to Incuna, come see me any time.</message>
            <response destination="incuna" message="Let's go back to Incuna."/>
        </dialog>
        <dialog name="incuna">
            <close/>
            <action teleport="/shattered_islands/world_2_87 5 6"/>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/cathi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Welcome, welcome... Heh-heh-heh...</message>
            <response destination="havetwo" message="Why do you have two brooms?"/>
        </dialog>
        <dialog name="havetwo">
            <message>That is none of your concern! Now go away before I get really mad!</message>
            <response destination="stealone" message="Did you steal one?"/>
        </dialog>
        <dialog name="stealone">
            <message>Keep it up, and you'll get more than you bargained for!</message>
            <response destination="stoleit" message="You stole it, didn't you."/>
        </dialog>
        <dialog name="stoleit">
            <say>Now you've done it!</say>
            <close/>
            <action enemy="player"/>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/rockforge/hrec_blackcopper.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Tread carefully, please, dear visitor! This farm is very important to us. Since Rockforge is a fortress, we usually do not go outside to collect timber, so we grow various plants here, inside the fortress.</message>
            <response destination="sunlight" message="Don't plants need sunlight?"/>
        </dialog>
        <dialog name="sunlight">
            <message>Yes, indeed. Just look up! It was quite amazing actually. We found this miles-long opening into the sky while digging tunnels. We reckon it is still part of the Giant Mountains, since it goes so high up! Anyway, we thought it may be good enough to grow plants, and it works!</message>
            <response destination="small" message="Those trees are somewhat small."/>
        </dialog>
        <dialog name="small">
            <message>Yes, yes. That is because we are still underground, and even the opening above us doesn't provide enough sunlight for them to grow as tall as trees on the surface. Still, it's good enough for our needs.</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/brynknot/aranarra.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Oh hello there! Did you happen to see my cat around here somewhere?</message>
            <response destination="cat" message="Your cat?"/>
        </dialog>
        <dialog name="cat">
            <message>Sadly, my cat has been missing since this giant hole formed... It may have something to do with it...</message>
            <message>I see that you are an adventurer... If you are going into the hole, I suggest you speak to Achetran the mage on the other side of the hole. He may have some information for you.</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/centennial/smug_student_witch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface state="class">
        <and>
            <check options="classTime"/>
        </and>
        <dialog name="hello">
            <message>Zzzzzzzz.....</message>
        </dialog>
        <dialog name="marisa" regex="marisa|kirisame|marisa kirisame">
            <message color="yellow">{npc.name} mumbles &quot;Love Sign: Master Spark&quot;.</message>
        </dialog>
    </interface>
    <interface state="club">
        <and>
            <check options="clubTime"/>
        </and>
        <dialog name="hello">
            <message>Heh. This sucker keeps falling for the same trick.</message>
            <response destination="cheating" message="Are you cheating?"/>
        </dialog>
        <dialog name="cheating">
            <message>It ain't cheating, I'm just playing creatively. Haha.~</message>
        </dialog>
        <dialog name="marisa" regex="marisa|kirisame|marisa kirisame">
            <message>Marisa's awesome isn't she?</message>
        </dialog>
    </interface>
</interfaces>
