=== DeusMagi/deusmagi-server/maps/schemas/ads-1.dtd
<!ELEMENT interfaces (interface*, quest?)>

<!ELEMENT quest (interface*, part*)>
<!ATTLIST quest
        name CDATA #REQUIRED
        repeat (1|0) #IMPLIED
        repeat_delay CDATA #IMPLIED>

<!ELEMENT part (info?, item?, kill?, interface*, part*)>
<!ATTLIST part
        uid CDATA #REQUIRED
        name CDATA #REQUIRED>

<!ELEMENT info (#PCDATA)>

<!ELEMENT item EMPTY>
<!ATTLIST item
        arch CDATA #IMPLIED
        name CDATA #IMPLIED
        nrof CDATA #IMPLIED
        keep (1|0) #IMPLIED>

<!ELEMENT kill EMPTY>
<!ATTLIST kill
        nrof CDATA #IMPLIED>

<!ELEMENT interface (code?, and?, dialog*)>
<!ATTLIST interface
        inherit CDATA #IMPLIED
        npc CDATA #IMPLIED
        state CDATA #IMPLIED>

<!ELEMENT code (#PCDATA)>

<!ELEMENT and (and|or|check|ncheck|message|choice|object|inherit|response|
        action|notification|close|say)*>

<!ELEMENT or (and|or|check|ncheck)*>

<!ELEMENT check (object?)>
<!ATTLIST check
        region_map CDATA #IMPLIED
        enemy (any|player) #IMPLIED
        started CDATA #IMPLIED
        finished CDATA #IMPLIED
        completed CDATA #IMPLIED
        failed CDATA #IMPLIED
        options CDATA #IMPLIED
        num2finish CDATA #IMPLIED
        faction_friend CDATA #IMPLIED
        gender (male|female|neuter|hermaphrodite) #IMPLIED)

<!ELEMENT ncheck (object?)>
<!ATTLIST ncheck
        region_map CDATA #IMPLIED
        enemy (any|player) #IMPLIED
        started CDATA #IMPLIED
        finished CDATA #IMPLIED
        completed CDATA #IMPLIED
        failed CDATA #IMPLIED
        options CDATA #IMPLIED
        num2finish CDATA #IMPLIED
        faction_friend CDATA #IMPLIED
        gender (male|female|neuter|hermaphrodite) #IMPLIED)

<!ELEMENT precond (#PCDATA)>

<!ELEMENT dialog ((message|choice|object|inherit|response|action|
        notification|close|say|and))>
<!ATTLIST dialog
        name CDATA #IMPLIED
        regex CDATA #IMPLIED
        inherit CDATA #IMPLIED
        icon CDATA #IMPLIED
        title CDATA #IMPLIED
        animation CDATA #IMPLIED>

<!ELEMENT message (#PCDATA,object*)>
<!ATTLIST message
        color CDATA #IMPLIED>

<!ELEMENT choice (message*)>

<!ELEMENT object EMPTY>
<!ATTLIST object
        arch CDATA #IMPLIED
        name CDATA #IMPLIED
        message CDATA #IMPLIED
        nrof CDATA #IMPLIED
        remove CDATA #IMPLIED>

<!ELEMENT inherit EMPTY>
<!ATTLIST inherit
        name CDATA #IMPLIED>

<!ELEMENT response EMPTY>
<!ATTLIST response
        message CDATA #REQUIRED
        destination CDATA #IMPLIED
        action CDATA #IMPLIED
        npc CDATA #IMPLIED>

<!ELEMENT action (#PCDATA)>
<!ATTLIST action
        start CDATA #IMPLIED
        complete CDATA #IMPLIED
        fail CDATA #IMPLIED
        region_map CDATA #IMPLIED
        enemy (player|clear) #IMPLIED
        teleport CDATA #IMPLIED
        trigger CDATA #IMPLIED
        cast CDATA #IMPLIED>

<!ELEMENT notification EMPTY>
<!ATTLIST notification
        message CDATA #REQUIRED
        action CDATA #IMPLIED
        shortcut CDATA #IMPLIED
        delay CDATA #IMPLIED>

<!ELEMENT close EMPTY>

<!ELEMENT say (#PCDATA)>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/galsteen.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Greetings adventurer. I'm {npc.name}, the captain of this outpost.</message>
            <message>Well, not really much of an outpost to be honest. We're here guarding this tunnel that connects Brynknot and Aris.</message>
            <response destination="bridge" message="Why is there no bridge?"/>
        </dialog>
        <dialog name="bridge">
            <message>We first tried building a bridge further east, but we have been unsuccessful because of the swift current. We didn't get much progress done, apart from some unstable foundation, which we have been unable to finish.</message>
            <message>If you're agile enough I suppose you could try using the foundation platforms to get from one side to the other. However, be careful, the current often gets stronger than usual, and it could catch you unaware and send you drowning into the river!</message>
            <message>So instead we built a tunnel here, after determining that the current is too swift even here.</message>
            <response destination="safe" message="How safe is the tunnel?"/>
        </dialog>
        <dialog name="safe">
            <message>Very safe! We are closely guarding it so no monsters can pass or take the tunnel as their own. Of course, there's the issue of some spider infestation. No one has seen the spiders so we've been unable to get rid of them, but the cobwebs just keep appearing after we remove them!</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/lyondale_archipelago/wizard/baldoth.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Welcome to the Wizards' Tower island in Lyondale Archipelago.</message>
            <message>If you are seeking the knowledge about Thelras or magic, I recommend you go see Teldach inside the tower.</message>
            <response destination="tellthelras" message="Tell me about Thelras."/>
            <response destination="whoteldach" message="Who is Teldach?"/>
        </dialog>
        <dialog name="tellthelras">
            <message>We Thelras are heavy users of magic. Spellcasting, wands, potions, horns, things like that. Our magic abilities are far greater than that of any other race.</message>
            <message>For more information, go see Teldach to learn about more about Thelras.</message>
            <response destination="whoteldach" message="Who is Teldach?"/>
        </dialog>
        <dialog name="whoteldach">
            <message>Teldach is the oldest of our race. He's just inside the tower; you should go see him.</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/lyondale_archipelago/wizard/teldach.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Welcome to the Wizards' Tower. This island is part of Lyondale Archipelago, mostly inhabited by Thelras.</message>
            <response destination="tellthelras" message="Tell me about Thelras."/>
        </dialog>
        <dialog name="tellthelras">
            <message>Thelras are a powerful, tall and fierce race. They excel in magic, where they can overpower even the strongest elvish spellcasters.</message>
            <message>Long ago, we Thelras decided to help the Thraal army in the fight against Zechna.</message>
            <message>Since most Thelras excel in magic as wizards, this tower was built for those who wanted to practice in the arts of magic.</message>
            <response destination="tellfight" message="Tell me about the fight."/>
            <response destination="telltower" message="Tell me about the tower."/>
        </dialog>
        <dialog name="tellfight">
            <message>We fought - and still do - together against Zechna, and became friends with the other races.</message>
            <message>Many humans, dwarves and other races come to this tower to learn about magic. Of course, when we first met the dwarves, we called them 'shorties', which made many of them furious. We eventually became friends with them, though.</message>
        </dialog>
        <dialog name="telltower">
            <message>In this tower you can find various things that could help you in using your magical skills, including shops with magic tools, spells, potions, and so on.</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/quests/lairwenn_notes/quest.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <quest name="Lairwenn's Notes">
        <interface inherit="Merchant.Seller" npc="Lairwenn" state="completed">
            <dialog name="hello">
                <message>Thank you for finding my notes earlier. Would you be interested in an extra writing pen?</message>
                <response destination="buy writing pen" message="Sure, tell me more."/>
                <response action="close" message="No thanks."/>
            </dialog>
            <dialog name="::buyitem">
                <message>Ah, good choice!</message>
                <inherit name="::buy"/>
                <message>Would you like to buy this top-quality writing pen?</message>
                <response destination="buy 1 writing pen" message="Sure."/>
                <response action="close" message="No thanks."/>
            </dialog>
            <dialog name="::boughtitem">
                <message>Here you go dear, a top-quality writing pen!</message>
            </dialog>
            <dialog name="::fail_money">
                <message>Oh dear, it seems you don't have enough money!</message>
            </dialog>
            <dialog name="::fail_weight">
                <message>Oh dear, you're not strong enough to hold this tiny writing pen?</message>
            </dialog>
        </interface>
        <part name="Finding the Notes" uid="get_notes">
            <info>Lairwenn has lost her notes somewhere in the Brynknot Library and she has asked you to find them for her, as she can't finish the document she is working on without them.</info>
            <item arch="note" name="Lairwenn's Notes"/>
            <interface npc="Lairwenn" state="need_start">
                <dialog name="hello">
                    <message>Welcome to the Brynknot Library... I'm {npc.name}, the librarian.</message>
                    <message>Please excuse me, I seem to have lost my notes somewhere...</message>
                    <response destination="lostnotes" message="You lost your notes?"/>
                </dialog>
                <dialog name="lostnotes">
                    <message>I hurriedly put them away while searching for this book, and then a while later I remembered about the notes but I can't find them now! And I really need them to finish this document I'm working on...</message>
                    <response destination="helpsearch" message="Can I help you in your search?"/>
                </dialog>
                <dialog name="helpsearch">
                    <message>I would certainly appreciate it my dear! The notes are somewhere in this library, I just can't seem to find them...</message>
                    <action start="get_notes"/>
                </dialog>
            </interface>
            <interface npc="Lairwenn" state="need_finish">
                <dialog name="hello">
                    <message color="yellow">{npc.name} sighs.</message>
                    <message>I'm trying to remember where I put them, but I just can't... Please continue your search my dear, they should be somewhere in this library...</message>
                </dialog>
            </interface>
            <interface npc="Lairwenn" state="need_complete">
                <dialog name="hello">
                    <message>You found my notes!</message>
                    <message>...</message>
                    <message>They were in the luggage on the top floor? How curious... Well, thank you my dear! I think I have something here that may be useful on your adventures... Now, where did I put it...</message>
                    <message color="yellow">{npc.name} thinks for a moment.</message>
                    <message>Just pulling your leg my dear! Here it is, a writing pen will be useful, will it not?</message>
                    <object name="writing pen"/>
                    <action complete="get_notes"/>
                </dialog>
            </interface>
        </part>
    </quest>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/centennial/studious_student_witch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface state="class">
        <and>
            <check options="classTime"/>
        </and>
        <dialog name="hello">
            <message>Hey. Listening to the teacher...</message>
        </dialog>
        <dialog name="alice" regex="alice|margatroid|alice margatroid">
            <message>Maybe later, I've really gotta pass this test.</message>
        </dialog>
    </interface>
    <interface state="club">
        <and>
            <check options="clubTime"/>
        </and>
        <dialog name="hello">
            <message>Too busy now. Trying to win against this cheater.</message>
            <response destination="cheating" message="Who is cheating?" npc="smug student witch"/>
        </dialog>
        <dialog inherit="hello" name="alice" regex="alice|margatroid|alice margatroid"/>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/asteria/princess_helena.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Can't you see I'm reading?</message>
            <response destination="reading" message="[b]You[/b] are reading?"/>
            <response action="close" message="Sorry."/>
        </dialog>
        <dialog name="reading">
            <message>Yes. Is it a crime for the daughter of a king to enjoy reading?</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/rockforge/fhod_grimfist.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface inherit="Tavern.Bartender">
        <dialog name="hello">
            <message color="yellow">*grumbles*</message>
            <message>Another customer... Very well... I am {npc.name}. What do you need? Make it quick, though.</message>
            <inherit name="::stock"/>
        </dialog>
        <dialog name="::buyitem">
            <message>Very well...</message>
            <inherit name="::buy"/>
            <message>How many do you want?</message>
            <inherit name="::stockitem"/>
        </dialog>
        <dialog name="::boughtitem">
            <message>There you go.</message>
            <inherit name="::boughtitem"/>
            <message>Now off with ya.</message>
        </dialog>
        <dialog name="::fail_weight">
            <message>What's this, you're not strong enough to carry that?</message>
        </dialog>
        <dialog name="::fail_money">
            <message>What's this, you don't have enough money?</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/centennial/lindy.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Hi, there {activator.name}. Welcome to the school library. Please try to keep quiet so others can study in peace.</message>
            <response destination="book" message="Find a book."/>
        </dialog>
        <dialog name="book">
            <message>We have plenty of books. Please feel free to ask Ruri if you need some assistance.</message>
            <response destination="ruri" message="Ask about Ruri."/>
            <response destination="touhou" message="Ask about the Eastern Project series."/>
            <response destination="main_menu" message="Ask about something else."/>
        </dialog>
        <dialog name="main_menu">
            <message>Was there anything else you wanted to talk about {activator.name}?</message>
            <response destination="book" message="Find a book."/>
            <response destination="ruri" message="Ask about Ruri."/>
            <response action="close" message="Goodbye."/>
        </dialog>
        <dialog name="touhou">
            <message>This name is, of course, translated from its original language, but it basically means the same thing. You should be able to find a copy in the library but it's very popular here so someone may be reading them right now.</message>
            <response destination="main_menu" message="Ask about something else."/>
        </dialog>
        <dialog name="ruri">
            <message>Don't mind her. She knows a bit too much but she's a hard worker. You wouldn't really expect most fairies to be that smart, though... it's kind of weird. I wonder if maybe I should ask the summoning instructor to look into the spell I used to summon her.</message>
            <response destination="main_menu" message="Ask about something else."/>
        </dialog>
        <dialog name="nanoha" regex="lindy harlaown|harlaown|nanoha|lyrical">
            <message>Excellent deduction. Yes, my parents were, indeed, quite the fans of the Nanoha series.</message>
            <response destination="main_menu" message="Ask about something else."/>
        </dialog>
        <dialog name="patchouli" regex="patchouli|patchouli knowledge">
            <message>Ah, I see you like the Eastern Project series, too. It's fairly obvious why I should be a fan of her, don't you think?</message>
            <response destination="main_menu" message="Ask about something else."/>
        </dialog>
    </interface>
</interfaces>
