=== DeusMagi/deusmagi-server/maps/schemas/ads-1.dtd
<!ELEMENT interfaces (interface*, quest?)>

<!ELEMENT quest (interface*, part*)>
<!ATTLIST quest
        name CDATA #REQUIRED
        repeat (1|0) #IMPLIED
        repeat_delay CDATA #IMPLIED>

<!ELEMENT part (info?, item?, kill?, interface*, part*)>
<!ATTLIST part
        uid CDATA #REQUIRED
        name CDATA #REQUIRED>

<!ELEMENT info (#PCDATA)>

<!ELEMENT item EMPTY>
<!ATTLIST item
        arch CDATA #IMPLIED
        name CDATA #IMPLIED
        nrof CDATA #IMPLIED
        keep (1|0) #IMPLIED>

<!ELEMENT kill EMPTY>
<!ATTLIST kill
        nrof CDATA #IMPLIED>

<!ELEMENT interface (code?, and?, dialog*)>
<!ATTLIST interface
        inherit CDATA #IMPLIED
        npc CDATA #IMPLIED
        state CDATA #IMPLIED>

<!ELEMENT code (#PCDATA)>

<!ELEMENT and (and|or|check|ncheck|message|choice|object|inherit|response|
        action|notification|close|say)*>

<!ELEMENT or (and|or|check|ncheck)*>

<!ELEMENT check (object?)>
<!ATTLIST check
        region_map CDATA #IMPLIED
        enemy (any|player) #IMPLIED
        started CDATA #IMPLIED
        finished CDATA #IMPLIED
        completed CDATA #IMPLIED
        failed CDATA #IMPLIED
        options CDATA #IMPLIED
        num2finish CDATA #IMPLIED
        faction_friend CDATA #IMPLIED
        gender (male|female|neuter|hermaphrodite) #IMPLIED)

<!ELEMENT ncheck (object?)>
<!ATTLIST ncheck
        region_map CDATA #IMPLIED
        enemy (any|player) #IMPLIED
        started CDATA #IMPLIED
        finished CDATA #IMPLIED
        completed CDATA #IMPLIED
        failed CDATA #IMPLIED
        options CDATA #IMPLIED
        num2finish CDATA #IMPLIED
        faction_friend CDATA #IMPLIED
        gender (male|female|neuter|hermaphrodite) #IMPLIED)

<!ELEMENT precond (#PCDATA)>

<!ELEMENT dialog ((message|choice|object|inherit|response|action|
        notification|close|say|and))>
<!ATTLIST dialog
        name CDATA #IMPLIED
        regex CDATA #IMPLIED
        inherit CDATA #IMPLIED
        icon CDATA #IMPLIED
        title CDATA #IMPLIED
        animation CDATA #IMPLIED>

<!ELEMENT message (#PCDATA,object*)>
<!ATTLIST message
        color CDATA #IMPLIED>

<!ELEMENT choice (message*)>

<!ELEMENT object EMPTY>
<!ATTLIST object
        arch CDATA #IMPLIED
        name CDATA #IMPLIED
        message CDATA #IMPLIED
        nrof CDATA #IMPLIED
        remove CDATA #IMPLIED>

<!ELEMENT inherit EMPTY>
<!ATTLIST inherit
        name CDATA #IMPLIED>

<!ELEMENT response EMPTY>
<!ATTLIST response
        message CDATA #REQUIRED
        destination CDATA #IMPLIED
        action CDATA #IMPLIED
        npc CDATA #IMPLIED>

<!ELEMENT action (#PCDATA)>
<!ATTLIST action
        start CDATA #IMPLIED
        complete CDATA #IMPLIED
        fail CDATA #IMPLIED
        region_map CDATA #IMPLIED
        enemy (player|clear) #IMPLIED
        teleport CDATA #IMPLIED
        trigger CDATA #IMPLIED
        cast CDATA #IMPLIED>

<!ELEMENT notification EMPTY>
<!ATTLIST notification
        message CDATA #REQUIRED
        action CDATA #IMPLIED
        shortcut CDATA #IMPLIED
        delay CDATA #IMPLIED>

<!ELEMENT close EMPTY>

<!ELEMENT say (#PCDATA)>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/lothost.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Hello there. I'm {npc.name} the wizard. I'm currently studying the abandoned mine north of here.</message>
            <response destination="tellmore" message="Tell me more..."/>
        </dialog>
        <dialog name="tellmore">
            <message>It's an abandoned dwarven mine that makes some sort of a tunnel between several locations. Rumor is that a portal to the legendary Temple of Zechna is located there, which is what I'm trying to find out about.</message>
            <message>If you are also interested in the mine, you can read about it in my notes in the bookcase.</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/asteria/agnes_marne.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>I see someone has found their way down here. Tell me, what can my shipping company do for you?</message>
            <response destination="shipping" message="Shipping?"/>
            <response destination="questions" message="I have some questions..."/>
            <response action="close" message="Goodbye."/>
        </dialog>
        <dialog name="shipping">
            <message>Sure, we ship lots of goods for the right price.</message>
            <response destination="questions" message="I have some questions..."/>
            <response action="close" message="Goodbye."/>
        </dialog>
        <dialog name="questions">
            <message>Some questions have answers that people don't like. Unless you have some business here, you should probably go.</message>
            <response action="close" message="Goodbye."/>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/centennial/madoka.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>*sigh* I wish they'd stop talking about those novels all day.</message>
        </dialog>
        <dialog name="patchouli" regex="patchouli|patchouli knowledge">
            <message>Well, they say Patchouli is a gateway herb, or character as the case may be... *chuckle*</message>
        </dialog>
        <dialog name="puella" regex="puella|puella magi madoka magica">
            <message>Yeah, everyone in town is named from one novel or other. The town is weird like that.</message>
        </dialog>
        <dialog name="contract">
            <message>What? Are you trying to pretend to be Kyubey or something?</message>
            <response destination="kyubey" message="Where is Kyubey?"/>
        </dialog>
        <dialog name="kyubey">
            <message>No, we don't have a Kyubey...</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/asteria/evelina_thash.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Welcome to the Asterian Royal Library, funded by our gracious king. Be sure to ask if you have any questions.</message>
            <response destination="king" message="The king?"/>
            <response destination="questions" message="I have some questions..."/>
        </dialog>
        <dialog name="king">
            <message>Believe it or not, King Romulus is quite generous to the intellectual pursuits.</message>
            <response destination="questions" message="I have some questions..."/>
        </dialog>
        <dialog name="questions">
            <message>The public area is free for all, but exercise your manners, please. The private area is only open to a privileged few. If you're unable to find a certain copy, notify me and I'll be sure to find it, as I have ample experience in this matter. If ever this becomes an issue, you had better first speak with me. I have more contacts than ways to name them.</message>
            <message>Be sure to ask if you need help with the categorization scheme.</message>
            <response destination="tellscheme" message="Tell me about the categorization scheme."/>
        </dialog>
        <dialog name="tellscheme">
            <message>The categorization scheme is rather simple at the moment. F denotes a fiction shelf. NF denotes a non-fiction shelf. The shelf is also labeled by general topic.</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/lyondale_archipelago/wizard/daril.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Have you heard about the legendary smoking pipe? They say it's the best pipe for smoking pipeweed.</message>
            <response destination="tellmore" message="Tell me more..."/>
        </dialog>
        <dialog name="tellmore">
            <message>If you smoke some pipeweed using that smoking pipe, you will be granted confusion and weapon magic protection, or so the rumour says.</message>
            <message>It has long been lost, however...</message>
            <response destination="location" message="Any ideas where it could be?"/>
        </dialog>
        <dialog name="location">
            <message>Well, some rumours say that the fierce dragon leader Scursaur has it in his possession.</message>
            <message>Of course, that's just a silly rumour... a dragon with a smoking pipe...</message>
            <response destination="aboutleader" message="Tell me about Scursaur."/>
        </dialog>
        <dialog name="aboutleader">
            <message>He is the leader of the dragons on the Dragons Island. Apparently it's possible to get to Dragons Island by completing the Underground Maze under Promethia Island.</message>
            <message>I wouldn't go there if I were you, though. The maze is one thing, but those dragons were sealed on that island for a reason...</message>
            <message>At any rate, the smoking pipe is most likely not even there, anyway. It would be a waste of time to go looking for it there.</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/brynknot/orlney_silvertongue.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Very impressive, adventurer! You found out about the illusionary wall, did you? Very well then.</message>
            <message>I'm {npc.name}, the president for Banks Inc.</message>
            <response destination="tellbanks" message="Tell me about Banks Inc..."/>
        </dialog>
        <dialog name="tellbanks">
            <message>Our job is to provide citizens of this world a way to access their funds from anywhere, including when paying from shops or when paying for various services.</message>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/ocean/sam_goodberry_to_strakewood.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>We have the right heading, {activator.name}. Why don't you go have a rest in the lower deck - I'll wake you up when we arrive in Brynknot on Strakewood Island.</message>
            <response destination="verywell" message="Very well."/>
        </dialog>
        <dialog name="verywell">
            <close/>
            <action teleport="/shattered_islands/incuna/ship_lower_deck_to_strakewood 2 11"/>
        </dialog>
    </interface>
</interfaces>

=== DeusMagi/deusmagi-server/maps/interfaces/strakewood_island/centennial/usagi.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE interfaces
  PUBLIC '-//Atrinik//ADS-1 1.1.2//EN'
  'ads-1.dtd'>
<interfaces>
    <interface>
        <dialog name="hello">
            <message>Hey! You don't look like one of my students...</message>
        </dialog>
        <dialog name="marisa" regex="marisa|kirisame|marisa kirisame">
            <message>Hey, I don't knock your hobbies.</message>
        </dialog>
        <dialog name="tsukino" regex="sailor moon|tsukino|usagi tsukino">
            <message>No, I won't do an &quot;In the name of the Moon&quot; speech for you. Go away.</message>
        </dialog>
    </interface>
</interfaces>
